name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.69
          components: rustfmt, clippy
          default: true
      - uses: pre-commit/action@v2.0.3
